fix: migrate from tap to node:test and c8
fastify/fastify-routes pull request #107
Opened 2024-08-15 02:10 UTC by dancastillo

#### Checklist

This PR removes `tap` and uses `node:test` and. `c8`

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-08-15 06:12 UTC, Uzlopak approved these changes
LGTM

2024-08-15 06:13 UTC, Uzlopak commented
Is c8 by default set for 100% Test coverage?

2024-08-15 06:43 UTC, gurgunday approved these changes

2024-08-15 06:49 UTC, gurgunday requested changes

2024-08-15 06:49 UTC, gurgunday commented on package.json
> +    "test:unit": "c8 node --test",
```suggestion
    "test:unit": "c8 --100 node --test",
```

2024-08-15 14:00 UTC, gurgunday approved these changes

2024-08-16 08:04 UTC, Eomm approved these changes

2024-08-16 08:04 UTC, merged