Add a changelog
fastify/fastify-routes pull request #32
Opened 2021-06-14 20:47 UTC by airhorns

Forgot this in #31, I think it'd be handy to explain the difference before releasing the major version. Nothing else right?

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [X] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2021-06-14 21:05 UTC, jsumners requested changes
The git log and releases page (https://github.com/fastify/fastify-routes/releases) constitutes the change log.

2021-06-14 22:50 UTC, airhorns commented
Whats the protocol for giving upgrade instructions? Manually created release notes?

2021-06-14 23:19 UTC, jsumners commented
How are the notes in this PR any different from adding them to the tagged release?

2021-06-14 23:34 UTC, airhorns commented
Yeah, I would use the same notes, I was just asking if that's what you wanted!

2021-06-14 23:46 UTC, jsumners commented
Yeah. That's typical.

2021-06-15 00:02 UTC, closed without merging

2021-06-15 13:02 UTC, jsumners commented
@airhorns do you have access to edit releases on this repo? If so, you can add a draft for v4.0.0 and it will automatically get attached to the tag when the tag is created.

2021-06-21 19:40 UTC, Eomm commented
I would tell that for this task we made https://github.com/fastify/releasify
Quite old but it still works